name: C2

# Menjalankan secara otomatis setiap 6 jam
on:
  schedule:
    - cron: '0 */6 * * *'  # Setiap 6 jam pada menit ke-0
  workflow_dispatch:

jobs:
  update-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "ducky"
          git config user.email "gkompor789@gmail.com"

      - name: Update README, commit, dan push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export TZ="Asia/Jakarta"
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S %Z")
          echo "Last updated: $TIMESTAMP" > README.md
          git add README.md
          git commit -m "Auto update README at $TIMESTAMP" || echo "No changes to commit"
          git push origin main
